// /**
// * This code was generated by v0 by Vercel.
// * @see https://v0.dev/t/a6szCW2fsDC
// * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
// */

// /** Add fonts into your Next.js project:

// import { Inter } from 'next/font/google'

// inter({
//   subsets: ['latin'],
//   display: 'swap',
// })

// To read more about using these font, please visit the Next.js documentation:
// - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
// - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
// **/
// import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
// import { ResponsiveBar } from "@nivo/bar"
// import { JSX, ClassAttributes, HTMLAttributes } from "react"

// export function Component() {
//   return (
//     <Card className=" w-full">
//       <CardHeader>
//         <CardTitle>Projections vs Actuals</CardTitle>
//       </CardHeader>
//       <CardContent>
//         <BarChart className="aspect-[15/4]" />
//       </CardContent>
//     </Card>
//   )
// }

// function BarChart(props: JSX.IntrinsicAttributes & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement>) {
//   return (
//     <div {...props}>
//       <ResponsiveBar
//         data={[
//           { name: "Jan", count: 111 },
//           { name: "Feb", count: 157 },
//           { name: "Mar", count: 129 },
//           { name: "Apr", count: 150 },
//           { name: "May", count: 119 },
//           { name: "Jun", count: 72 },
//           {name:"July", count: 80},
//           {name:"Aug", count: 85},
//           {name:"Sept", count: 90},
//           {name:"Oct", count: 75},
//           {name:"Nov", count: 95},
//           {name:"Dec", count: 100},
//         ]}
//         keys={["count"]}
//         indexBy="name"
//         margin={{ top: 20, right: 0, bottom: 40, left: 40 }}
//         padding={0.3}
//         colors={["yellow"]}
//         axisBottom={{
//           tickSize: 0,
//           tickPadding: 16,
//         }}
//         axisLeft={{
//           tickSize: 0,
//           tickValues: 4,
//           tickPadding: 10,
//         }}
//         gridYValues={4}
//         theme={{
//           tooltip: {
//             chip: {
//               borderRadius: "9999px",
//             },
//             container: {
//               fontSize: "8px",
//               textTransform: "capitalize",
//               borderRadius: "1px",
//             },
//           },
//           grid: {
//             line: {
//               stroke: "#f3f4f6",
//             },
//           },
//         }}
//         tooltipLabel={({ id }) => `${id}`}
//         enableLabel={false}
//         role="application"
//         ariaLabel="A bar chart showing data"
//       />
//     </div>
//   )
// }


import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { ResponsiveBar } from "@nivo/bar";
import { JSX, ClassAttributes, HTMLAttributes } from "react";
import { barChartData } from "@/Data/componentdata"; // Import the data from data.js

export function Component() {
  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle>Projections vs Actuals</CardTitle>
      </CardHeader>
      <CardContent>
        <BarChart className="aspect-[15/4]" />
      </CardContent>
    </Card>
  );
}

function BarChart(props: JSX.IntrinsicAttributes & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement>) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={barChartData} // Use the imported data here
        keys={["count"]}
        indexBy="name"
        margin={{ top: 20, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["yellow"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 10,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "8px",
              textTransform: "capitalize",
              borderRadius: "1px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data"
      />
    </div>
  );
}
